### ISSUE TITLE
Rust doc building tendril fails

### ISSUE THREAD

**Issue by Ygg01** [servo/tendril#27]
I've been getting a failure on current nightly for rustdoc, when building tendril.

Here is the relevant part of the log:
https://travis-ci.org/Ygg01/xml5ever/jobs/140435008#L390

Perhaps tendril should be built by nightly.es to help automatically detect these errors?

**Comment by SimonSapin** [comment]
Yes, this is likely https://github.com/rust-lang/rust/issues/34423. Looks like it’s fixed now, it should be in the next nightly. (`rustup update` gives me ad7fe6521 2016-06-23 right now.)

I saw the error through https://github.com/SimonSapin/run-nightly (my ad-hoc nightli.es from before nightli.es existed) several days ago, but the Rust issue was already filed.

Closing as I think there’s nothing to do in this repo.
