### ISSUE TITLE
Support io::Read directly into a Tendril

### ISSUE THREAD

**Issue by kmcallister** [servo/tendril#4]
This entails adding a method for formats (or at least `Read`-supporting formats) that decides how many bytes at the end of a buffer represent an incomplete character -- these should be deferred until the next chunk.

**Comment by kmcallister** [comment]
[Relevant code](https://github.com/servo/html5ever/pull/114/files#diff-4eb21974b8413ea7abca83d1ff99ba6eR471) in an earlier iteration of this library.

**Comment by kmcallister** [comment]
Actually I don't think html5ever would use this. We don't know whether bytes represent UTF-8 when we read them off the network. Rather, we need an API to turn a stream of byte tendrils in some encoding into a stream of string tendrils. In the case where the source encoding is UTF-8, this should happen without copying — other than characters that span a chunk boundary, and these will always fit in an inline tendril.

The obvious choice to represent a stream of tendrils is an iterator. But I think a "push" interface would fit better with the rest of html5ever than the "pull" interface of the `Iterator` trait. I'll think more about this.

**Comment by arthurprs** [comment]
I wanted the same so I created a set_len method, see #22

**Comment by SimonSapin** [comment]
`BytesTendril` now implements `DerefMut`, so it’s possible to get a `&mut [u8]` to pass to `std::io::Read`. This can (unsafely) be used together with the `push_uninitialized` method.

See for example https://github.com/servo/tendril/blob/9e6490a462895ca8728cb2ac4aa361cf0635775d/src/stream.rs#L64-L86

Decoding UTF-8 can be done separately. See the rest of `src/stream.rs`.
