### ISSUE TITLE
Link to docs.rs in readme

### ISSUE THREAD

**Issue by Luro02** [servo/tendril#48]
Most of the docs are hosted on docs.rs, which I can access very fast, but with https://doc.servo.org/tendril/index.html I have to wait quite some time for a page to load.

It could imagine to keep the `API documentation` link in the readme and add a badge, that links to https://docs.rs/tendril/

An example of such a badge can be seen here https://github.com/KokaKiwi/rust-hex/blob/master/README.md

**Comment by brightly-salty** [comment]
I think this should be closed? I see this implemented on my end. Probably just forgotten about.
