### ISSUE TITLE
Release tendril 0.4.2

### ISSUE THREAD

**Issue by xfix** [servo/tendril#50]
I think it makes sense to release a new version with soundness fixes. In particular, currently Tendril is pretty much broken with allocators that actually care about alignment parameter as in the current version on crates.io the alignment of `Tendril` is 1, which is incorrect as the library stores extra information within its pointer and this breaks when an allocator returns a pointer with alignment of 1.

**Comment by SimonSapin** [comment]
I’m very out of the loop. Are you referring to fixes that still need to be made, or fixes that have been merged on github but not published on crates.io?

**Comment by xfix** [comment]
Merged but not published.

**Comment by SimonSapin** [comment]
https://crates.io/crates/tendril/0.4.2 is up!
